a = int(input("Enter 1st no: "))
b = int(input("Enter 2nd no: "))
print(" ")
print(f"Additon of {a} and {b} = {a+b}")
print(f"Subtraction of {a} and {b} = {a-b}")
print(f"Multiplication of {a} and {b} = {a*b}")
print(f"Division of {a} and {b} = {a/b}")
print(f"Remainder of {a} and {b} = {a%b}")
print(f"Exponent of {a} and {b} = {a**b}")
print(f"Float Divison of {a} and {b} = {a//b}")